export const icons = {
  logo: "/Images/logos/main-logo.svg",
  whiteLogo: "/Images/logos/white-logo.svg",
  twitter: "/Images/logos/twitter.svg",
  instagarm: "/Images/logos/instagram.svg",
  facebook: "/Images/logos/facebook.svg",
  youtube: "/Images/logos/youtube.svg",

  twitterlpf: "/Images/logos/twitter-lpf.svg",
  facebooklpf: "/Images/logos/facebook-lpf.svg",
  instagarmlpf: "/Images/logos/instagram-lpf.svg",

  uploadLogo: "/Images/icons/upload-logo.svg",
  arrowDownIcon: "/Images/icons/arrow-down.svg",
  sendSqaureIcon: "/Images/icons/send-sqaure.svg",
  printIconIcon: "/Images/icons/printer-icon.svg",
  addCircleIcon: "/Images/icons/add-circle.svg",
  addCircleOutlinedIcon: "/Images/icons/add-circle-outlined.svg",
  tickIcon: "/Images/icons/tick-icon.svg",
  colorPickerPaletteIcon: "/Images/icons/color-picker-palette-icon.svg",
  invoiceIcon: "/Images/icons/invoice-icon.svg",
  clientsIcon: "/Images/icons/clients-icon.svg",
  settingsIcon: "/Images/icons/settings-icon.svg",
  firstInvoiceIcon: "/Images/icons/crt-first-invoice-icon.svg",
  searchIcon: "/Images/icons/search-icon.svg",
  filterIcon: "/Images/icons/filter-icon.svg",
  plusIcon: "/Images/icons/plus-icon.svg",
  threeDotsIcon: "/Images/icons/three-dots-icon.svg",
  editIcon: "/Images/icons/edit-icon.svg",
  profileIcon: "/Images/icons/profile-icon.svg",
  logoutIcon: "/Images/icons/logout-icon.svg",
  viewIcon: "/Images/icons/view-icon.svg",
  deleteIcon: "/Images/icons/delete-icon.svg",
  deleteRedIcon: "/Images/icons/delete-Red-icon.svg",
  watermarkIcon: "/Images/icons/watermark-icon.svg",
  copyIcon: "/Images/icons/copy-icon.svg",
  whatsappIcon: "/Images/icons/whatsapp-icon.svg",
  facebookIcon: "/Images/icons/facebook-icon.svg",
  twitterIcon: "/Images/icons/twitter-icon.svg",
  personIcon: "/Images/icons/person-icon.svg",
  cameraIcon: "/Images/icons/camera-icon.svg",
  editWhiteIcon: "/Images/icons/edit-white-icon.svg",
  openEyeIcon: "/Images/icons/open-eye-icon.svg",
  closeEyeIcon: "/Images/icons/close-eye-icon.svg",
  sortIcon: "/Images/icons/sort-icon.svg",
  easyUseIcon: "/Images/icons/easy-use-icon.svg",
  customColorIcon: "/Images/icons/custom-color-icon.svg",
  freeGenerateIcon: "/Images/icons/free-generate-icon.svg",

  educationIcon: "/Images/icons/education-icon.svg",
  fitnessIcon: "/Images/icons/fitness-icon.svg",
  beautyIcon: "/Images/icons/beauty-icon.svg",
  officialsIcon: "/Images/icons/officials-icon.svg",
  medicalIcon: "/Images/icons/medical-icon.svg",
  eventsIcon: "/Images/icons/events-icon.svg",
  plusCircleIcon: "/Images/icons/plus-circle-icon.svg",
  minusCircleIcon: "/Images/icons/minus-circle-icon.svg",
};

export const backendURL =
  process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:3005";

export const frontendUrl =
  process.env.NEXT_PUBLIC_GOOGLE_CALLBACK_URL || "http://localhost:3000";
